### ISSUE TITLE
有关于数据集的问题。

### ISSUE THREAD

**Issue by LuckyDL21** [yuh-yang/KGCL-SIGIR22#10]
你好，首先谢谢你分享我的好研究。 我有一个疑问，所以问您。

请问Yelp18数据集的rawdata是从哪里找到的？ 请分享一下，谢谢。

**Comment by yuh-yang** [comment]
Hi! Please find the raw data at [this](https://www.kaggle.com/datasets/yelp-dataset/yelp-dataset), and our processed data is aligned with that in [this repo](https://github.com/gusye1234/LightGCN-PyTorch). :)

**Comment by LuckyDL21** [comment]
Thank you!
