### ISSUE TITLE
Amazon-book的KG数据问题

### ISSUE THREAD

**Issue by Lilyzhangyanlin** [yuh-yang/KGCL-SIGIR22#11]
感谢作者分享数据集和源码！

我在查看amazon-book的KG数据集时发现实体数量只有24915个，与论文中的entity数量（29714）不符而与item数量（24915）相同。请问amazon-book的kg图是只包含item而不包含其它类型的实体吗？以及在KG图中发现了（0， 0， 0）这样的三元组，请问这种自连的三元组的含义又是什么呢？

**Comment by yuh-yang** [comment]
你好，在处理形如{(h,r,t)}KG数据时，为了简化，我们生成的kg.txt中，h全部为item，t全部为外部entity，并且它们的编号是独立的，均从0开始，这一点与代码中model.py:line56相一致

(0,0,0)是一条有意义的kg记录，这是因为它们均是有效的one_hot编码，并非padding
