### ISSUE TITLE
Amazon数据集中如何通过TransE得到实体嵌入

### ISSUE THREAD

**Issue by FKCHAN** [yuh-yang/KGCL-SIGIR22#12]
你好，最近在研究Amazon数据集的推荐，对您的论文很感兴趣，但是在论文中没有看到通过TransE得到实体嵌入的过程，如果方便能否发我一份，不胜感激
我的邮箱：fukun@hrbeu.edu.cn

**Comment by yuh-yang** [comment]
你好，TransE和推荐任务协同训练，相关代码可以在model.py::calc_kg_loss_transE(self, h, r, pos_t, neg_t)找到
