### ISSUE TITLE
请问大佬，有处理数据集的代码吗

### ISSUE THREAD

**Issue by zhaijianyang** [yuh-yang/KGCL-SIGIR22#13]
本人刚接触知识图谱推荐，请问有处理数据集的代码吗，或相关链接。谢谢啦

**Comment by yuh-yang** [comment]
你好！对于常用的数据集例如Amazon-Book和Yelp，可以直接采用处理后的数据。对于新的数据集，可以参考这些工作制作自己的KG数据集：
https://github.com/danyang-liu/NewsGraphRec
https://github.com/WHUIR/KOPRA

**Comment by ByronLaw1025** [comment]
请问lastfm、movielen、book crossing这几个数据集哪里能找到处理后的数据呢？一直没找到能直接用的

**Comment by yuh-yang** [comment]
可以参考下相关工作release出来的code和data，这几个应该都有囊括

KGAT, KGIN, MCCLK, ...
