### ISSUE TITLE
what's the purpose of "get_ui_views_weighted"

### ISSUE THREAD

**Issue by lihuiliullh** [yuh-yang/KGCL-SIGIR22#16]
May I know what function "get_ui_views_weighted" does?

**Comment by yuh-yang** [comment]
Hi, @lihuiliullh !

`get_ui_views_weighted` refers to Section 3.3 **Knowledge-Guided Contrastive Learning** in our KGCL paper, where we generate masks on user-item edges based on item-specific KG structure consistency to obtain noise-free user-item graph views.

**Comment by lihuiliullh** [comment]
@yuh-yang 
I have another question. Why do you calculate degree_weights? It seems like you don't use it at all.
![image](https://user-images.githubusercontent.com/53407011/226150552-d593f23d-cf00-4f72-aef8-67361749b604.png)

**Comment by yuh-yang** [comment]
Yes. It is not used in KGCL. The purpose was about ablation, where we used degree-generated weights for adaptive augmentation, instead of structure consistency weights to validate if this mechanism works individually.

**Comment by yuh-yang** [comment]
Closed for being inactive.
