### ISSUE TITLE
关于训练集测试集

### ISSUE THREAD

**Issue by zxs9494la** [yuh-yang/KGCL-SIGIR22#18]
作者您好，我注意到运行结果只有test指标，数据集划分是8：2的训练集和测试集。这是不需要验证集吗，还有就是对于指标的选择是在test中选一个出色的吗，我对于这个比较疑惑。

**Comment by yuh-yang** [comment]
你好，我们的setting和LightGCN/NGCF等工作一致，在训练集中再划分出10%的数据作为验证集来选择超参数，总的划分是7:1:2
