### ISSUE TITLE
计算pui的代码问题

### ISSUE THREAD

**Issue by wangxin211** [yuh-yang/KGCL-SIGIR22#19]
根据论文中的公式，这里为什么是除而不是乘呢。
![image](https://user-images.githubusercontent.com/57390278/233885253-95d6d402-4dbb-4e55-b076-c46d61d62e69.png)

**Comment by yuh-yang** [comment]
Hi, @wangxin211 ,

这步除法是为了计算论文中公式的$p_a \cdot \mu_{p^\prime}$，即用预先定义的keep_rate除以计算出的keep_rate的均值来得到放缩的系数。论文中为了方便表达写成了乘法的形式，可以理解为这步除法是在计算论文中$p_a \cdot \mu_{p^\prime}$这一项的整体
