### ISSUE TITLE
数据集的问题

### ISSUE THREAD

**Issue by GCodertf** [yuh-yang/KGCL-SIGIR22#20]
作者您好，我刚接触知识图谱。我的数据是excel表里任务的信息已经投标者中标情况，怎么变成你代码能跑的数据啊？您代码里的KG.txt这个文件是什么意思啊，后面的test.txt怎么得到的啊？

**Comment by yuh-yang** [comment]
你好，KG.txt是知识图谱的三元组文件，格式为h,r,t，其中h和t是entity id，r是relation id

test.txt是数据的测试集，通过7:1:2划分得到

**Comment by GCodertf** [comment]
> 你好，KG.txt是知识图谱的三元组文件，格式为h,r,t，其中h和t是entity id，r是relation id
> 
> test.txt是数据的测试集，通过7:1:2划分得到

您好，KG.txt我已经明白其中的意思了，只有实体id和关系id。是否分别有给实体和关系进行编号的文件，只是在代码文件里面没有放出来

**Comment by yuh-yang** [comment]
从0开始编号就可以
