### ISSUE TITLE
关于是否有压低baselines的问题

### ISSUE THREAD

**Issue by Shane953** [yuh-yang/KGCL-SIGIR22#21]
我发现你们的KG数据集和KGAT,KGIN或者KGCN的都不一样，并且许多模型在你们的数据集上往往能跑出更高的性能，
如SGL在你们的yelp2018数据集
参数设置：  -n_layer 2 -lambda 0.1 -droprate 0.1 -augtype 1 -temp 0.2
 实际结果： Epoch: 18, Hit Ratio:0.06962  |  Precision:0.01922  |  Recall:0.07812  |  NDCG:0.05111
远高于论文中所汇报的值

**Comment by yuh-yang** [comment]
你好，感谢你对我们工作的关注，

对于数据集问题，我们使用了KGAT放出的Yelp以及Amazon-Book，进一步在原始数据的基础上过滤掉了由item出发2-hop以上的triplets，这一预处理是为了和我们使用的MIND数据集的处理方式保持一致（新闻中的实体以及知识关系很丰富，收集3-hop以及上的关系是比较昂贵的）

SGL的表现问题，在我们进行实验的2021年summer，SGL并没有官方的Pytorch release，为了方便对比，我们在当前repo下实现了SGL原文中提出的表现最好的SGL-ED-3，参数设置与你report的唯一差异在于n_layer，这里我们采用了3而不是2

我们对于SGL的测试结果是：Epoch 11, {'precision': array([0.01782416]), 'recall': array([0.07194972]), 'ndcg': array([0.04752995])}

不是很清楚你使用了哪个repo的SGL实现，如果在Yelp数据集上SGL-ED-2的效果要好过三层的，那这个问题确实是我们实验当中的疏忽，当时对于SGL进行grid-search的时候，并没有把层数这一超参数包括进来，我们会在数据集上尝试SGL-ED-2的结果，并且更新baseline模型的最佳参数到这个repo里面，

感谢你提出的问题，欢迎进一步交流

**Comment by yuh-yang** [comment]
另外，如果将KGCL的KG aggregation部分实现为基于edge的多跳GNN，相比baselines可以有更大的提升，你可以尝试一下，目前这个repo中的实现为了simplicity只是1-hop聚合

**Comment by Shane953** [comment]
我使用的是https://github.com/Coder-Yu/SELFRec  中的SGL

**Comment by yuh-yang** [comment]
SELFRec框架和LightGCN的源码对于训练样本的采样实现方式是有差异的，前者会保证一个epoch可以过完所有的training pairs，而LightGCN的采样则不一定，随机性更大一些。可以试试保证采样方式一致的情况下再去重新比较KGCL和baselines（这里我们比较的时候都是用的LightGCN的采样方式），模型的性能应该会同时上涨或者下降，但是一般相对的性能顺序是保持稳定的

另外，看你昨天也提到了SimGCL的效果比KG模型好很多的问题，这里潜在的原因一个是上面提到的采样方式，另外就是SimGCL是GCL4Rec最新的SOTA模型，效果好于一些之前发表的KGRec方法也是正常的，在SimGCL发表后我们也没有测试过在同样数据上它与KGCL的性能比较。而目前KG这条线的fundamental模型已经转为KGIN这种基于异质图神经网络的模型，许多后续的新工作例如KGIC、KACL的源码都是基于KGIN二次开发，可以试试这些更新的KGRec方法的性能会不会好于SimGCL。而且我们的经验是，一般在越稀疏的数据集上，使用KG的优势要越明显

**Comment by Shane953** [comment]
好的，感谢你的回复
