### ISSUE TITLE
specific package version

### ISSUE THREAD

**Issue by xga0** [yuh-yang/KGCL-SIGIR22#22]
Thank you for sharing the code!

I got the "sparse tensors do not have storage" error message when running the code. I suspect it is caused by the incorrect torch-sparse version.

Can you share the specific version information of the following packages?
torch (requirements.txt shows 1.8.1)
torch-cluster
torch-scatter
torch-sparse
torch-spline-conv
torch-geometric (requirements.txt shows 1.7.2)

Thank you!

**Comment by yuh-yang** [comment]
Hi, torch-sparse should be around 2.0.4. That's the only external package we use for PyG.

You can also try to deploy the newest PyG lib and see if it works. And if the error continues to be raised, you can try our [new implementation](https://github.com/HKUDS/KGRec) which should work well in more recent PyG libs.

**Comment by xga0** [comment]
Thanks for your prompt reply! Actually, I also tried the new implementation, and I did not encounter this error. But I ran into a new issue [here](https://github.com/HKUDS/KGRec/issues/1#issue-1816198807).
