### ISSUE TITLE
 Benefits of KGCL in Alleviating Noise Effect

### ISSUE THREAD

**Issue by liliiop** [yuh-yang/KGCL-SIGIR22#23]
您好，请问关于验证知识图谱噪声影响的部分是如何进行实验的，即如何实现在训练时添加噪声，并保持测试时不变，可否给出相应代码，谢谢

**Comment by yuh-yang** [comment]
你好，

我们这里的做法是随机生成x%的三元组作为噪声添加到训练用的知识图谱中，即h,r,t各自随机抽样组合成噪声三元组

**Comment by liliiop** [comment]
您好，感谢您的回答，想请教一下是如何在训练时使用添加噪声的三元组，测试时用原三元组的呢，代码主要在哪部分进行改进呢

**Comment by yuh-yang** [comment]
可以直接修改kg.txt，添加噪声为kg_noise.txt，并且在dataloader中为训练指定读入这个文件即可
