### ISSUE TITLE
I have some questions about the source code and would like to ask you

### ISSUE THREAD

**Issue by kaishuibujiatang** [yuh-yang/KGCL-SIGIR22#3]
1. In the world.py file, **ROOT_PATH = "./"** on line 10, is there a dot missing on the right?

2. In contrast. Py, the **import worldpip** line 10 is wrong？

3. In the contrat. py file, Line 231 **d_inv[np.isINF (d_inv)] = 0.**.  Do I have to set the number on the right hand side?

**Comment by yuh-yang** [comment]
Hi.
1. you should modify the root_path to your currently correct path.
2. contrast.py, line 10 is importing world.py
3. you can set it to 1 to enable self-connection, or just leave it to 0.
