### ISSUE TITLE
I would like to consult you about the ablation experiment

### ISSUE THREAD

**Issue by kaishuibujiatang** [yuh-yang/KGCL-SIGIR22#5]
How should I note or modify which section to perform the KGA and KGC module ablation experiments separately？
**all_models = ['lgn', 'kgc', 'sgl', 'sgl-rgat']**， 'kgc' and 'sgl-rgat' in this statement stand for KGA and KGC respectively？
Thank you very much

**Comment by yuh-yang** [comment]
Hi. For ablation KGA, please set `world.uicontrast=="RANDOM"`; and for KGC, please turn off knowledge graph contrastive learning by disabling `world.kgc_enable`.

**Comment by kaishuibujiatang** [comment]
ok, thank you very much.
