### ISSUE TITLE
Hello, I encountered a problem when I reproduced the code. I tried the solutions on the Internet without success. Can you help me take a look? Plz~

### ISSUE THREAD

**Issue by SSDZyf** [yuh-yang/KGCL-SIGIR22#6]
RuntimeError:
Tried to access nonexistent attribute or method 'crow_indices' of type 'Tensor'.:
  File "D:\Pycharm\KGCL\kgcl\lib\site-packages\torch_sparse\tensor.py", line 109
    def from_torch_sparse_csr_tensor(self, mat: torch.Tensor,
                                     has_value: bool = True):
        rowptr = mat.crow_indices()
                 ~~~~~~~~~~~~~~~~ <--- HERE
        col = mat.col_indices()

**Comment by SSDZyf** [comment]
Problem solved after I reinstall torch_sparse==0.6.10

**Comment by user683** [comment]
> Problem solved after I reinstall torch_sparse==0.6.10
Thanks for your solution. it‘s work.
