### ISSUE TITLE
论文结果复现问题

### ISSUE THREAD

**Issue by Lilyzhangyanlin** [yuh-yang/KGCL-SIGIR22#7]
感谢作者分享源码！

在Amazon-book数据集上直接运行源码，本机上的最佳结果在140轮停止迭代，recall为0.1397，与原文中0.1496存在较大差距。

想请问作者这是什么原因呢~

**Comment by yuh-yang** [comment]
你好，我们将KGCL在没有验证集的Amazon-Book数据集上的训练日志上传在[log/Amazon-Book.log](https://github.com/yuh-yang/KGCL-SIGIR22/blob/main/log/Amazon-Book.log)，希望能够帮助你复现结果:)

**Comment by Lilyzhangyanlin** [comment]
好的感谢！本机上使用的参数和训练日志上的一致，但在三个数据集上好像都仍然难以达到原文中的最佳结果。能否请作者解答一下可能会有哪些原因使复现结果存在偏差呢~

**Comment by yuh-yang** [comment]
你好 @Lilyzhangyanlin , 注意到code中并未指定`random.seed()`以及设置cudnn的`torch.backends.cudnn.deterministic = True`, 从而导致随机因素的潜在干扰。此外，我们发现CUDA环境也常常会对各类模型的表现产生影响。我们实验的环境为CUDA11.0+RTX3090. 希望这些信息能够帮助你:)

**Comment by Lilyzhangyanlin** [comment]
好的，非常感谢！

**Comment by Kid-Young** [comment]
> 感谢作者分享源码！
> 
> 在Amazon-book数据集上直接运行源码，本机上的最佳结果在140轮停止迭代，recall为0.1397，与原文中0.1496存在较大差距。
> 
> 想请问作者这是什么原因呢~

我复现的时候遇到以下这个问题
![image](https://user-images.githubusercontent.com/56811268/186863466-0ff0e7b5-3575-4dd7-8122-ce3e5217e99e.png)
请问怎么解决？ 谢谢

**Comment by Kid-Young** [comment]
你好，我复现的时候遇到以下这个问题：
![image](https://user-images.githubusercontent.com/56811268/186864470-8c394b90-5815-4c6b-93c5-3e498e882a3f.png)
请问怎么解决？
谢谢
