### ISSUE TITLE
你好，关于论文中公式（8）有点不理解

### ISSUE THREAD

**Issue by kaishuibujiatang** [yuh-yang/KGCL-SIGIR22#8]
你好，请问图中圈出来的**X**分别代表什么意思呢，方便可以解答一下嘛，感谢。
![image](https://user-images.githubusercontent.com/90997061/188888125-580ebb42-068e-4881-a4f9-a3b8149dd684.png)

**Comment by kaishuibujiatang** [comment]
![image](https://user-images.githubusercontent.com/90997061/188893945-09babca2-ea91-4a9b-befc-f862ded39f08.png)
这张图片是公式的上下文

**Comment by Genius-pig** [comment]
论文里有说明，X1n表示一个键值对，就是来自view1的用户和物品的向量表示。
![image](https://github.com/yuh-yang/KGCL-SIGIR22/assets/26118649/5f2b1bae-1913-43bb-8cd6-6d99af218194)
