### ISSUE TITLE
regarding kg

### ISSUE THREAD

**Issue by Antoniozxm** [yuh-yang/KGCL-SIGIR22#9]
感谢作者分享源码！
想请问下作者关于知识图谱的问题，请问kg.txt中的entity_id和relation_id是怎么如何获取的呢？另外train.txt里的id是entity id还是word2id的index啊 还是说作者是把review text里的词都当做实体给予entity id再提取到kg.txt中？
麻烦啦

**Comment by zzh0227** [comment]
同问！
